// lib/reporting.ts
import type { CloudSession } from "@/lib/firestore";

export function buildClinicianReportHTML(params: {
  session: CloudSession;
  stats: any;
  quality: any;
  gait?: any;
}) {
  const { session, stats, quality, gait } = params;
  const created = session.createdAt?.toDate?.() ?? new Date(session.createdAtMs);

  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <title>KnexFlex Report</title>
      <style>
        body { font-family: ui-sans-serif, system-ui; margin: 24px; color: #0f172a; }
        h1 { margin: 0 0 8px 0; font-size: 22px; }
        .muted { color: #475569; font-size: 12px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-top: 16px; }
        .card { border: 1px solid #e2e8f0; border-radius: 14px; padding: 12px; }
        .kv { display: grid; grid-template-columns: 1fr 1fr; gap: 6px 12px; margin-top: 8px; font-size: 13px; }
        .kv div:nth-child(odd) { color: #475569; }
        .tag { display: inline-block; margin-right: 6px; padding: 2px 8px; border: 1px solid #e2e8f0; border-radius: 999px; font-size: 11px; color:#334155; }
        hr { border: none; border-top: 1px solid #e2e8f0; margin: 16px 0; }
        pre { white-space: pre-wrap; font-size: 12px; color:#334155; }
      </style>
    </head>
    <body>
      <h1>KnexFlex – Clinical Session Report</h1>
      <div class="muted">
        Session: <b>${escapeHtml(session.displayName ?? session.title)}</b> •
        ${escapeHtml(created.toLocaleString())}
      </div>

      <div style="margin-top:10px;">
        ${(session.tags ?? []).map((t) => `<span class="tag">${escapeHtml(t)}</span>`).join("")}
      </div>

      <div class="grid">
        <div class="card">
          <b>Summary</b>
          <div class="kv">
            <div>Samples</div><div>${stats?.sampleCount ?? session.sampleCount}</div>
            <div>Duration</div><div>${(stats?.durationSec ?? 0).toFixed(2)} s</div>
            <div>ROM</div><div>${(stats?.rom ?? 0).toFixed(1)}°</div>
            <div>Mean</div><div>${(stats?.mean ?? 0).toFixed(1)}°</div>
            <div>StDev</div><div>${(stats?.stdev ?? 0).toFixed(2)}°</div>
            <div>Reps</div><div>${stats?.reps ?? 0}</div>
          </div>
        </div>

        <div class="card">
          <b>Signal Quality</b>
          <div class="kv">
            <div>Score</div><div>${Math.round(quality?.score ?? 0)}/100</div>
            <div>Jitter</div><div>${(quality?.jitter ?? 0).toFixed(2)}°</div>
            <div>Dropouts</div><div>${(quality?.dropoutRate ?? 0).toFixed(1)}%</div>
            <div>Clipping</div><div>${(quality?.clippingRate ?? 0).toFixed(1)}%</div>
          </div>
        </div>
      </div>

      <hr />

      <div class="card">
        <b>Notes</b>
        <div class="muted" style="margin-top:6px;">${escapeHtml(session.notes ?? "") || "—"}</div>
      </div>

      ${
        gait
          ? `
        <hr />
        <div class="card">
          <b>Gait Cycle (Normalized)</b>
          <div class="kv">
            <div>Heel Strike Index</div><div>${gait.heelStrikeIndex}</div>
            <div>Toe Off Index</div><div>${gait.toeOffIndex}</div>
            <div>Peak Flexion</div><div>${gait.peakFlexion?.toFixed?.(1) ?? gait.peakFlexion}°</div>
            <div>Peak Extension</div><div>${gait.peakExtension?.toFixed?.(1) ?? gait.peakExtension}°</div>
          </div>
          <pre>${escapeHtml(JSON.stringify(gait.averageCycle?.slice?.(0, 10) ?? [], null, 2))}</pre>
          <div class="muted">Note: chart visuals are available in-app; this report keeps data portable and printable.</div>
        </div>
        `
          : ""
      }

      <div class="muted" style="margin-top:18px;">
        Generated by KnexFlex Pro • Print this page to “Save as PDF”.
      </div>
    </body>
  </html>
  `;
}

export function openPrintWindow(html: string) {
  const w = window.open("", "_blank", "width=980,height=720");
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 250);
}

function escapeHtml(s: string) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
